### ISSUE TITLE
Not available on pypi anymore

### ISSUE THREAD

**Issue by molobrakos** [molobrakos/eliqonline#14]
eliqonline seems to have disappeared from pypi. Was this by accident?

**Comment by 6d66** [comment]
Transferd to @molobrakos  😄

**Comment by 6d66** [comment]
Thank you @molobrakos!

**Comment by 6d66** [comment]
Ops, you prehaps want to close the issue when pypi is sloved. sorry!

**Comment by molobrakos** [comment]
https://pypi.org/project/eliqonline/
